### ISSUE TITLE
Textures missing

### ISSUE THREAD

**Issue by MennoMekes** [KIT-IAI/SDM_Plugin_General#1]
In the previous version (FZKViewer x64 V 6.5.1) textures in IFC were shown:
![image](https://github.com/KIT-IAI/SDM_Plugin_General/assets/66679121/8679860b-8a5e-4cf1-b05d-595e70058b55)

But with the same settings in the latest KITviewer I cannot see them.
Did something change in some default settings I'm missing?

**Comment by arch1501** [comment]
@MennoMekes Thanks for your feedback. Could you please provide us with a test file so that we can check the problem.

**Comment by MennoMekes** [comment]
Ofcourse:

[Housing_IFC4_SKP24.zip](https://github.com/KIT-IAI/SDM_Plugin_General/files/15235219/Housing_IFC4_SKP24.zip)

**Comment by arch1501** [comment]
@MennoMekes Thanks, unfortunately the texture is missing in the archive.

**Comment by MennoMekes** [comment]
Ah, I thought it was exported in the IFC itself....

![Nuance - HV WF Magnolia_3](https://github.com/KIT-IAI/SDM_Plugin_General/assets/66679121/113fb39c-dac9-4518-8dbc-1bd46a746146)

**Comment by arch1501** [comment]
@MennoMekes In your example an external texture files is used, but it would also be possible with IFC to store the texture in a IfcBlobTexture if this is supported by SketchUp.
I was able to fix the problem and with the next update to version 7.2 the texture will be displayed again. However, it would be better if the texture coordinates were also saved in IFC via IfcTextureMap. Otherwise the application has to try to determine the texture coordinates itself.

**Comment by MennoMekes** [comment]
Thanks!
I have no idea. I'll ask Jan Brouwer about this since he is the creator of the Ifc manager for SketchUP.
